format = "$directory$git_branch$git_status$character"

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[$modified$staged$untracked]($style) "
style = "yellow"
modified = "*"
staged = "+"
untracked = "?"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
